// src/use-cases/quality-manufacturing/quality-manufacturing.vue
<template>
  <KanbanUseCaseDemo :scenario="QUALITY_MANUFACTURING_SCENARIO" />
</template>

<script setup lang="ts">
import KanbanUseCaseDemo from '../kanban-use-case-demo.vue';
import { QUALITY_MANUFACTURING_SCENARIO } from './quality-manufacturing.data';
import './quality-manufacturing.scss';
</script>

// src/use-cases/quality-manufacturing/quality-manufacturing.react.tsx
import KanbanUseCaseDemo from '../kanban-use-case-demo.react';
import { QUALITY_MANUFACTURING_SCENARIO } from './quality-manufacturing.data';
import './quality-manufacturing.scss';

export default function QualityManufacturingUseCase() {
  return <KanbanUseCaseDemo scenario={QUALITY_MANUFACTURING_SCENARIO} />;
}
