// src/use-cases/kanban-use-case-demo.vue
<template>
  <section :class="shellClass" :aria-label="scenario.title">
    <header class="kanban-use-case-header">
      <div class="kanban-use-case-header__main">
        <div class="kanban-use-case-identity">
          <span class="kanban-use-case-eyebrow">{{ scenario.eyebrow }}</span>
          <strong class="kanban-use-case-title">{{ scenario.title }}</strong>
        </div>
        <div class="kanban-use-case-metrics">
          <div
            v-for="metric in scenario.metrics"
            :key="metric.label"
            :class="`kanban-use-case-metric kanban-use-case-metric--${metric.tone ?? 'neutral'}`"
          >
            <strong class="kanban-use-case-metric__value">{{ metric.value }}</strong>
            <span class="kanban-use-case-metric__label">{{ metric.label }}</span>
          </div>
        </div>
      </div>
      <div :class="`kanban-use-case-status kanban-use-case-status--${scenario.attention.tone}`">
          <span class="kanban-use-case-status__dot" aria-hidden="true" />
          <span><strong>{{ scenario.attention.label }}:</strong> {{ scenario.attention.detail }}</span>
      </div>
    </header>
    <RevoGrid
      class="kanban-use-case-grid"
      hide-attribution
      resize
      :source="gridRows"
      :columns="columns"
      :plugins="plugins"
      :column-types="columnTypes"
      :additional-data="additionalData"
      :kanban.prop="kanban"
      :theme="isDark ? 'darkCompact' : 'compact'"
    />
  </section>
</template>

<script setup lang="ts">
import './kanban-use-case-demo.scss';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import RevoGrid, { type GridPlugin } from '@revolist/vue3-datagrid';
import { KanbanPlugin } from '@revolist/revogrid-enterprise';
import type { KanbanUseCaseScenario } from './kanban-use-case-model';
import { createKanbanUseCaseConfig, kanbanUseCaseShellClass, resolveKanbanUseCaseDark } from './kanban-use-case-model';
import { currentTheme, observeCurrentTheme } from '../theme';

const props = defineProps<{ scenario: KanbanUseCaseScenario }>();
const gridRows = ref([...props.scenario.cards]);
const columns = [...props.scenario.columns];
const plugins: GridPlugin[] = [KanbanPlugin];
const columnTypes = {};
const additionalData = computed(() => ({}));
const kanban = computed(() => createKanbanUseCaseConfig(props.scenario));
const hostIsDark = ref(currentTheme().isDark());
const isDark = computed(() => resolveKanbanUseCaseDark(props.scenario, hostIsDark.value));
const shellClass = computed(() => kanbanUseCaseShellClass(props.scenario, hostIsDark.value));
let disconnectTheme: (() => void) | undefined;

onMounted(() => {
  disconnectTheme = observeCurrentTheme((dark) => {
    hostIsDark.value = dark;
  });
});
onBeforeUnmount(() => disconnectTheme?.());
</script>

// src/use-cases/kanban-use-case-demo.react.tsx
import './kanban-use-case-demo.scss';
import { useEffect, useMemo, useState } from 'react';
import { RevoGrid } from '@revolist/react-datagrid';
import { KanbanPlugin } from '@revolist/revogrid-enterprise';
import type { KanbanUseCaseScenario } from './kanban-use-case-model';
import { createKanbanUseCaseConfig, kanbanUseCaseShellClass, resolveKanbanUseCaseDark } from './kanban-use-case-model';
import { currentTheme, observeCurrentTheme } from '../theme';

export default function KanbanUseCaseDemo({ scenario }: { scenario: KanbanUseCaseScenario }) {
  const [hostIsDark, setHostIsDark] = useState(() => currentTheme().isDark());
  const isDark = resolveKanbanUseCaseDark(scenario, hostIsDark);
  const source = useMemo(() => [...scenario.cards], [scenario]);
  const columns = useMemo(() => [...scenario.columns], [scenario]);
  const plugins = useMemo(() => [KanbanPlugin], []);
  const columnTypes = useMemo(() => ({}), []);
  const additionalData = useMemo(() => ({}), []);
  const kanban = useMemo(() => createKanbanUseCaseConfig(scenario), [scenario]);

  useEffect(() => observeCurrentTheme(setHostIsDark), []);

  return (
    <section
      className={kanbanUseCaseShellClass(scenario, hostIsDark)}
      aria-label={scenario.title}
    >
      <header className="kanban-use-case-header">
        <div className="kanban-use-case-header__main">
          <div className="kanban-use-case-identity">
            <span className="kanban-use-case-eyebrow">{scenario.eyebrow}</span>
            <strong className="kanban-use-case-title">{scenario.title}</strong>
          </div>
          <div className="kanban-use-case-metrics">
            {scenario.metrics.map((metric) => (
              <div key={metric.label} className={`kanban-use-case-metric kanban-use-case-metric--${metric.tone ?? 'neutral'}`}>
                <strong className="kanban-use-case-metric__value">{metric.value}</strong>
                <span className="kanban-use-case-metric__label">{metric.label}</span>
              </div>
            ))}
          </div>
        </div>
        <div className={`kanban-use-case-status kanban-use-case-status--${scenario.attention.tone}`}>
          <span className="kanban-use-case-status__dot" aria-hidden="true" />
          <span><strong>{scenario.attention.label}:</strong> {scenario.attention.detail}</span>
        </div>
      </header>
      <RevoGrid
        className="kanban-use-case-grid"
        hideAttribution
        resize
        source={source}
        columns={columns}
        plugins={plugins}
        columnTypes={columnTypes}
        additionalData={additionalData}
        kanban={kanban}
        theme={isDark ? 'darkCompact' : 'compact'}
      />
    </section>
  );
}
