// src/kanban.vue
<template>
  <div class="kanban-showcase">
    <RevoGrid
      class="kanban-showcase__grid"
      hide-attribution
      resize
      :source="gridRows"
      :columns="columns"
      :plugins="plugins"
      :column-types="columnTypes"
      :additional-data="additionalData"
      :kanban.prop="kanban"
      :theme="isDark ? 'darkCompact' : 'compact'"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import RevoGrid, { type GridPlugin } from '@revolist/vue3-datagrid';
import { KanbanPlugin } from '@revolist/revogrid-enterprise';
import { currentThemeVue } from './shared/theme';
import { createKanbanShowcaseConfig, KANBAN_SHOWCASE_COLUMNS, resolveKanbanRows, type KanbanShowcaseCard } from './kanban.shared';
import './kanban.scss';

const props = defineProps<{ rows?: KanbanShowcaseCard[] }>();
const { isDark } = currentThemeVue();
const gridRows = ref(resolveKanbanRows(props.rows));
const columns = KANBAN_SHOWCASE_COLUMNS;
const plugins: GridPlugin[] = [KanbanPlugin];
const columnTypes = {};
const additionalData = computed(() => ({}));
const kanban = computed(() => createKanbanShowcaseConfig());
</script>

// src/kanban.react.tsx
import { useMemo } from 'react';
import { RevoGrid } from '@revolist/react-datagrid';
import { KanbanPlugin } from '@revolist/revogrid-enterprise';
import { currentTheme } from './shared/theme';
import { createKanbanShowcaseConfig, KANBAN_SHOWCASE_COLUMNS, resolveKanbanRows, type KanbanShowcaseCard } from './kanban.shared';
import './kanban.scss';

export default function KanbanShowcase({ rows }: { rows?: KanbanShowcaseCard[] }) {
  const source = useMemo(() => resolveKanbanRows(rows), [rows]);
  const columns = useMemo(() => KANBAN_SHOWCASE_COLUMNS, []);
  const plugins = useMemo(() => [KanbanPlugin], []);
  const columnTypes = useMemo(() => ({}), []);
  const additionalData = useMemo(() => ({}), []);
  const kanban = useMemo(() => createKanbanShowcaseConfig(), []);

  return (
    <div className="kanban-showcase">
      <RevoGrid
        className="kanban-showcase__grid"
        hideAttribution
        resize
        source={source}
        columns={columns}
        plugins={plugins}
        columnTypes={columnTypes}
        additionalData={additionalData}
        kanban={kanban}
        theme={currentTheme().isDark() ? 'darkCompact' : 'compact'}
      />
    </div>
  );
}
